FROM node:12-alpine3.12

RUN apk add git
RUN mkdir -p /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY . /app/

RUN yarn && yarn build

RUN tar cfz ethhmy-bridge-be.tgz dist

CMD /bin/bash
